"""empty message

Revision ID: 1316e674b162
Revises: caba4425853f
Create Date: 2020-04-21 01:04:34.398711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1316e674b162'
down_revision = 'caba4425853f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.String(length=500), nullable=False))
    op.add_column('Venue', sa.Column('genres', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###
