"""empty message

Revision ID: 74482ea7d030
Revises: 5e3f6f7dc6c1
Create Date: 2020-04-21 10:47:36.774215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74482ea7d030'
down_revision = '5e3f6f7dc6c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Show', 'Venue', ['venue_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_column('Show', 'venue_id')
    # ### end Alembic commands ###
