"""empty message

Revision ID: a149291fe53e
Revises: b626208e5670
Create Date: 2020-04-21 00:59:09.449895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a149291fe53e'
down_revision = 'b626208e5670'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Artist_name_key', 'Artist', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Artist_name_key', 'Artist', ['name'])
    # ### end Alembic commands ###
